### ISSUE TITLE
java.security.InvalidKeyException: Illegal key size

### ISSUE THREAD

**Issue by afterbit01** [mervick/aes-everywhere#5]
Hello,
i have tried

String encrypted = Aes256.encrypt("TEXT", "PASSWORD");
      System.out.println(encrypted);

but i get 👍 
java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at encrypturl.Aes256.encrypt(Aes256.java:64)

**Comment by mervick** [comment]
On a default JDK installation, AES is limited to 128 bit key size. In order to perform 256-bit AES encryption, you will need to download and install Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files.

https://deveshsharmablogs.wordpress.com/2012/10/09/fixing-java-security-invalidkeyexception-illegal-key-size-exception/

**Comment by mervick** [comment]
https://www.andreafortuna.org/programming/java-tips-how-to-fix-the-invalidkeyexception-illegal-key-size-or-default-parameters-runtime/

**Comment by afterbit01** [comment]
thank you! it works!
